### ISSUE TITLE
Reverse math can be very fragile

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/reverse_asciidoctor#12]
With the SP 800-90B document, we can see that reverse math processing is very fragile.

We need to do something about it, and it might again be a parsing issue that can be done using a MathML gem.

**Comment by opoudjis** [comment]
This gem use mathml2asciimath gem. We could just choose to block the Mathml to asciimath conversion, and just leave ooxml to Mathml conversion, now that metanorma supports native Mathml.

**Comment by ronaldtse** [comment]
Are you suggesting that we accept MathML in Metanorma AsciiDoc as input too? (In addition to AsciiMath) 

That would be a good idea BTW. We can accept different math syntaxes as input (AsciiMath, Latex math, MathML).

**Comment by opoudjis** [comment]
I'm convinced we already do.

That's the problem with you constantly getting me to add features onto Metaorma. You can no longer track either.

**Comment by ronaldtse** [comment]
> We can accept different math syntaxes as input (AsciiMath, Latex math, MathML).

I don't think this is done though?

e.g.

```
[stem,latexmath]
--
M =
 \begin{bmatrix}
  -\sin λ_0 & \cos λ_0 & 0 \\
  -\sin φ_0 \cos λ_0 & -\sin φ_0 \sin λ_0 & \cos φ_0 \\
  \cos φ_0 \cos λ_0 & \cos φ_0 \sin λ_0 & \sin φ_0
 \end{bmatrix}
--
```

vs

MathML

```xml
[stem,mathml]
--
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <mi>M</mi>
    <mo>=</mo>
    <mrow>
      <mo>[</mo>
      <mtable columnspacing="5pt" displaystyle="true" rowspacing="0pt">
...
    </mrow>
  </mrow>
</math>
--
```

vs AsciiMath:
```
[stem,asciimath]
--
a = 1
--
```

**Comment by opoudjis** [comment]
Action: Option to convert to asciimath, or to stop at mathml. Latex is indeed not implemented yet. 

MathML is picked up currently simply by seeing if there is a `<math` or`<...:math` at the start of the stem expression; so the second option should be working.

**Comment by opoudjis** [comment]
The functionality not to convert MathML to AsciiMath is already there, and is indeed default functionality for the script; it's just that I hadn't noticed before because Metanorma used to require AsciiMath.

* `bundle exec bin/w2a ith.docx > ith.adoc` leaves the MathML alone
* `bundle exec bin/w2a --mathml2asciimath ith.docx > ith.adoc` converts the MathML to AsciiMath

Noted in Readme.
